rainforest2/config/routes.rb
Rainforest2::Application.routes.draw do

  resources :products
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  root :to => "products#index"

end

rainforest2/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price_in_cents

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def formatted_price
  price_in_dollars = price_in_cents.to_f / 100
  sprintf("%.2f", price_in_dollars)
  end
end

rainforest2/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest

  has_secure_password
  validates_presence_of :password, :on => :create
end

rainforest2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

rainforest2/app/controllers/products_controller.rb
class ProductsController < ApplicationController

 # GET /products
 # GET /products.json
 def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  endnd
  end
 	
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
  
end

rainforest2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end

end

rainforest2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

rainforest2/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest2/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest2/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest2/app/helpers/users_helper.rb
module UsersHelper
end

rainforest2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Rainforest2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>

    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>
</body>

</html>

rainforest2/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rainforest2/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

rainforest2/app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to "New Product", "/products/new" %>

<%= @products.each do |product| %>
<p><%= product[:name] %>,<%= product[:description] %>, <%= product[:price_in_cents] %></p>
<% end %>

rainforest2/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', products_path %>

rainforest2/app/views/products/show.html.erb
<h1>Products</h1>

<%= link_to "Back to Products", products_url %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %> 

<p><%= product[:name] %>, <%= product[:description] %>, <% product[:price_in_cents] %>
</p>

rainforest2/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rainforest2/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>